export const GET_ALL_COFFEE = 'GET_ALL_COFFEE';
export const GET_ALL_COFFEE_SUCCESS = 'GET_ALL_COFFEE_SUCCESS';
export const GET_ALL_COFFEE_FAILURE = 'GET_ALL_COFFEE_FAILURE';
export const ORDER_COFFEE = 'ORDER_COFFEE';
export const ORDER_COFFEE_SUCCESS = 'ORDER_COFFEE_SUCCESS';
export const ORDER_COFFEE_FAILURE = 'ORDER_COFFEE_FAILURE';